const fs = require('fs');
const input = [
  {"pertanyaan": "卵 (たまご)", "jawaban": "Telur[cite: 4]"},
  {"pertanyaan": "肉 (にく)", "jawaban": "Daging[cite: 4]"},
  {"pertanyaan": "魚 (さかな)", "jawaban": "Ikan[cite: 4]"},
  {"pertanyaan": "飲みます (のみます)", "jawaban": "Minum[cite: 4]"},
  {"pertanyaan": "食べます (たべます)", "jawaban": "Makan[cite: 4]"},
  {"pertanyaan": "水 (みず)", "jawaban": "Air[cite: 4]"},
  {"pertanyaan": "新しい (あたらしい)", "jawaban": "Baru[cite: 4]"},
  {"pertanyaan": "小さい (ちいさい)", "jawaban": "Kecil[cite: 4]"},
  {"pertanyaan": "大きい (おおきい)", "jawaban": "Besar[cite: 4]"},
  {"pertanyaan": "一分 (いっぷん / いちふん)", "jawaban": "Menit[cite: 4]"},
  {"pertanyaan": "一時 (いちじ)", "jawaban": "Jam[cite: 4]"},
  {"pertanyaan": "古い (ふるい)", "jawaban": "Lama[cite: 4]"},
  {"pertanyaan": "火曜日 (かようび)", "jawaban": "Hari Selasa[cite: 4]"},
  {"pertanyaan": "月曜日 (げつようび)", "jawaban": "Hari Senin[cite: 4]"},
  {"pertanyaan": "半 (はん)", "jawaban": "Setengah[cite: 4]"},
  {"pertanyaan": "金曜日 (きんようび)", "jawaban": "Hari Jumat[cite: 4]"},
  {"pertanyaan": "木曜日 (もくようび)", "jawaban": "Hari Kamis[cite: 4]"},
  {"pertanyaan": "水曜日 (すいようび)", "jawaban": "Hari Rabu[cite: 4]"},
  {"pertanyaan": "言います (いいます)", "jawaban": "Berkata[cite: 4]"},
  {"pertanyaan": "日曜日 (にちようび)", "jawaban": "Hari Minggu[cite: 4]"},
  {"pertanyaan": "土曜日 (どようび)", "jawaban": "Hari Sabtu[cite: 4]"},
  {"pertanyaan": "見ます (みます)", "jawaban": "Melihat[cite: 4]"},
  {"pertanyaan": "読みます (よみます)", "jawaban": "Membaca[cite: 4]"},
  {"pertanyaan": "話します (はなします)", "jawaban": "Berbicara[cite: 4]"},
  {"pertanyaan": "一 (いち)", "jawaban": "Satu[cite: 4]"},
  {"pertanyaan": "書きます (かきます)", "jawaban": "Menulis[cite: 4]"},
  {"pertanyaan": "聞きます (ききます)", "jawaban": "Mendengarkan[cite: 4]"},
  {"pertanyaan": "四 (よん)", "jawaban": "Empat[cite: 4]"},
  {"pertanyaan": "三 (さん)", "jawaban": "Tiga[cite: 4]"},
  {"pertanyaan": "二 (に)", "jawaban": "Dua[cite: 4]"},
  {"pertanyaan": "七 (なな)", "jawaban": "Tujuh[cite: 4]"},
  {"pertanyaan": "六 (ろく)", "jawaban": "Enam[cite: 4]"},
  {"pertanyaan": "五 (ご)", "jawaban": "Lima[cite: 4]"},
  {"pertanyaan": "十 (じゅう)", "jawaban": "Sepuluh[cite: 4]"},
  {"pertanyaan": "九 (きゅう)", "jawaban": "Sembilan[cite: 4]"},
  {"pertanyaan": "八 (はち)", "jawaban": "Delapan[cite: 4]"},
  {"pertanyaan": "一年 (いちねん)", "jawaban": "Tahun[cite: 4]"},
  {"pertanyaan": "一月 (いちがつ)", "jawaban": "Bulan[cite: 4]"},
  {"pertanyaan": "一日 (ついたち / いちにち)", "jawaban": "Tanggal[cite: 4]"},
  {"pertanyaan": "南 (みなみ)", "jawaban": "Selatan[cite: 4]"},
  {"pertanyaan": "西 (にし)", "jawaban": "Barat[cite: 4]"},
  {"pertanyaan": "東 (ひがし)", "jawaban": "Timur[cite: 4]"},
  {"pertanyaan": "北 (きた)", "jawaban": "Utara[cite: 4]"},
  {"pertanyaan": "口 (ぐち)", "jawaban": "Pintu -[cite: 4]"},
  {"pertanyaan": "東口 (ひがしぐち)", "jawaban": "Pintu Timur[cite: 4]"},
  {"pertanyaan": "北口 (きたぐち)", "jawaban": "Pintu Utara[cite: 4]"},
  {"pertanyaan": "南口 (みなみぐち)", "jawaban": "Pintu Selatan[cite: 4]"},
  {"pertanyaan": "西口 (にしぐち)", "jawaban": "Pintu Barat[cite: 4]"},
  {"pertanyaan": "買います (かいます)", "jawaban": "Membeli[cite: 4]"},
  {"pertanyaan": "買い物 (かいもの)", "jawaban": "Belanja[cite: 4]"},
  {"pertanyaan": "お金 (おかね)", "jawaban": "Uang[cite: 4]"},
  {"pertanyaan": "千 (せん)", "jawaban": "1000[cite: 4]"},
  {"pertanyaan": "百 (ひゃく)", "jawaban": "100[cite: 4]"},
  {"pertanyaan": "一円 (いちえん)", "jawaban": "Yen[cite: 4]"},
  {"pertanyaan": "万 (まん)", "jawaban": "10000[cite: 4]"},
  {"pertanyaan": "百円 (ひゃくえん)", "jawaban": "100 Yen[cite: 4]"},
  {"pertanyaan": "千円 (せんえん)", "jawaban": "1000 Yen[cite: 4]"},
  {"pertanyaan": "来ます (きます)", "jawaban": "Datang[cite: 4]"},
  {"pertanyaan": "行きます (いきます)", "jawaban": "Pergi[cite: 4]"},
  {"pertanyaan": "一万円 (いちまんえん)", "jawaban": "10.000 Yen[cite: 4]"},
  {"pertanyaan": "合います (あいます)", "jawaban": "Bertemu[cite: 4]"},
  {"pertanyaan": "休みます (やすみます)", "jawaban": "Libur[cite: 4]"},
  {"pertanyaan": "日本 (にほん)", "jawaban": "Jepang[cite: 4]"},
  {"pertanyaan": "東京 (とうきょう)", "jawaban": "Tokyo[cite: 4]"},
  {"pertanyaan": "私 (わたし)", "jawaban": "Saya[cite: 4]"},
  {"pertanyaan": "父 (ちち)", "jawaban": "Ayah[cite: 4]"},
  {"pertanyaan": "男 (おとこ)", "jawaban": "Laki-laki[cite: 4]"},
  {"pertanyaan": "子供 (こども)", "jawaban": "Anak[cite: 4]"},
  {"pertanyaan": "母 (はは)", "jawaban": "Ibu[cite: 4]"},
  {"pertanyaan": "女 (おんな)", "jawaban": "Perempuan[cite: 4]"},
  {"pertanyaan": "お父さん (おとうさん)", "jawaban": "Ayah oranglain[cite: 4]"},
  {"pertanyaan": "お母さん (おかあさん)", "jawaban": "Ibu Oranglain[cite: 4]"},
  {"pertanyaan": "外国 (がいこく)", "jawaban": "Luar Negeri[cite: 4]"},
  {"pertanyaan": "国 (くに)", "jawaban": "Negara[cite: 4]"},
  {"pertanyaan": "何人 (なんにん)", "jawaban": "Berapa Orang?[cite: 4]"},
  {"pertanyaan": "~語 (~ご)", "jawaban": "Bahasa -[cite: 4]"},
  {"pertanyaan": "日本語 (にほんご)", "jawaban": "B. Jepang[cite: 4]"},
  {"pertanyaan": "英語 (えいご)", "jawaban": "B. Inggris[cite: 4]"},
  {"pertanyaan": "日本人 (にほんじん)", "jawaban": "Orang Jepang[cite: 4]"},
  {"pertanyaan": "~人 (~じん / にん)", "jawaban": "-Orang[cite: 4]"},
  {"pertanyaan": "中国語 (ちゅうごくご)", "jawaban": "B. China[cite: 4]"},
  {"pertanyaan": "好き (すき)", "jawaban": "Suka[cite: 4]"},
  {"pertanyaan": "本 (ほん)", "jawaban": "Buku[cite: 4]"},
  {"pertanyaan": "読書 (どくしょ)", "jawaban": "Bacaan[cite: 4]"},
  {"pertanyaan": "夏 (なつ)", "jawaban": "Musim Panas[cite: 4]"},
  {"pertanyaan": "春 (はる)", "jawaban": "Musim Semi[cite: 4]"},
  {"pertanyaan": "何 (なに)", "jawaban": "Apa?[cite: 4]"},
  {"pertanyaan": "秋 (あき)", "jawaban": "Musim Gugur[cite: 4]"},
  {"pertanyaan": "冬 (ふゆ)", "jawaban": "Musim Dingin[cite: 4]"},
  {"pertanyaan": "今 (いま)", "jawaban": "Sekarang[cite: 4]"},
  {"pertanyaan": "道 (みち)", "jawaban": "Jalan[cite: 4]"},
  {"pertanyaan": "風 (かぜ)", "jawaban": "Angin[cite: 4]"},
  {"pertanyaan": "花 (はな)", "jawaban": "Bunga[cite: 4]"},
  {"pertanyaan": "通り (とおり)", "jawaban": "Jalan[cite: 4]"},
  {"pertanyaan": "空 (そら)", "jawaban": "Langit[cite: 4]"},
  {"pertanyaan": "海 (うみ)", "jawaban": "Laut[cite: 4]"},
  {"pertanyaan": "右 (みぎ)", "jawaban": "Kanan[cite: 4]"},
  {"pertanyaan": "町 (まち)", "jawaban": "Kota[cite: 4]"},
  {"pertanyaan": "山 (やま)", "jawaban": "Gunung[cite: 4]"},
  {"pertanyaan": "左 (ひだり)", "jawaban": "Kiri[cite: 4]"},
  {"pertanyaan": "店 (みせ)", "jawaban": "Toko[cite: 4]"},
  {"pertanyaan": "川 (かわ)", "jawaban": "Sungai[cite: 4]"},
  {"pertanyaan": "一つ (ひとつ)", "jawaban": "1 Buah[cite: 4]"},
  {"pertanyaan": "人気 (にんき)", "jawaban": "Popularitas[cite: 4]"},
  {"pertanyaan": "今日 (きょう)", "jawaban": "Hari Ini[cite: 4]"},
  {"pertanyaan": "二つ (ふたつ)", "jawaban": "2 Buah[cite: 4]"},
  {"pertanyaan": "多い (おおい)", "jawaban": "Banyak[cite: 4]"},
  {"pertanyaan": "天気 (てんき)", "jawaban": "Cuaca[cite: 4]"},
  {"pertanyaan": "赤い (あかい)", "jawaban": "Merah[cite: 4]"},
  {"pertanyaan": "少ない (すくない)", "jawaban": "Sedikit[cite: 4]"},
  {"pertanyaan": "晴れ (はれ)", "jawaban": "Cerah[cite: 4]"},
  {"pertanyaan": "青い (あおい)", "jawaban": "Biru[cite: 4]"},
  {"pertanyaan": "高い (たかい)", "jawaban": "Mahal / Tinggi[cite: 4]"},
  {"pertanyaan": "雨 (あめ)", "jawaban": "Hujan[cite: 4]"},
  {"pertanyaan": "黒い (くろい)", "jawaban": "Hitam[cite: 4]"},
  {"pertanyaan": "安い (やすい)", "jawaban": "Murah[cite: 4]"},
  {"pertanyaan": "雪 (ゆき)", "jawaban": "Salju[cite: 4]"},
  {"pertanyaan": "白い (しろい)", "jawaban": "Putih[cite: 4]"},
  {"pertanyaan": "広い (ひろい)", "jawaban": "Luas[cite: 4]"},
  {"pertanyaan": "雲 (くも)", "jawaban": "Awan[cite: 4]"},
  {"pertanyaan": "大学 (だいがく)", "jawaban": "Universitas[cite: 4]"},
  {"pertanyaan": "前 (まえ)", "jawaban": "Sebelum[cite: 4]"},
  {"pertanyaan": "人 (ひと)", "jawaban": "Orang[cite: 4]"},
  {"pertanyaan": "先生 (せんせい)", "jawaban": "Guru[cite: 4]"},
  {"pertanyaan": "後 (あと)", "jawaban": "Setelah[cite: 4]"},
  {"pertanyaan": "時間 (じかん)", "jawaban": "Waktu[cite: 4]"},
  {"pertanyaan": "学生 (がくせい)", "jawaban": "Murid[cite: 4]"},
  {"pertanyaan": "朝 (あさ)", "jawaban": "Pagi[cite: 4]"},
  {"pertanyaan": "場所 (ばしょ)", "jawaban": "Tempat[cite: 4]"},
  {"pertanyaan": "一年生 (いちねんせい)", "jawaban": "Kelas -[cite: 4]"},
  {"pertanyaan": "昼 (ひる)", "jawaban": "Siang[cite: 4]"},
  {"pertanyaan": "駅 (えき)", "jawaban": "Stasiun[cite: 4]"},
  {"pertanyaan": "勉強 (べんきょう)", "jawaban": "Pelajaran[cite: 4]"},
  {"pertanyaan": "夜 (よる)", "jawaban": "Malam[cite: 4]"},
  {"pertanyaan": "日 (ひ)", "jawaban": "Matahari[cite: 4]"},
  {"pertanyaan": "文化 (ぶんか)", "jawaban": "Kebudayaan[cite: 4]"},
  {"pertanyaan": "乗ります (のります)", "jawaban": "Naik[cite: 4]"},
  {"pertanyaan": "出かけます (でかけます)", "jawaban": "Meninggalkan Rumah[cite: 4]"},
  {"pertanyaan": "音楽 (おんがく)", "jawaban": "Musik[cite: 4]"},
  {"pertanyaan": "旅行 (りょこう)", "jawaban": "Wisata[cite: 4]"},
  {"pertanyaan": "留学 (りゅうがく)", "jawaban": "Study Luar Negeri[cite: 4]"},
  {"pertanyaan": "学校 (がっこう)", "jawaban": "Sekolahan[cite: 4]"},
  {"pertanyaan": "小学校 (しょうがっこう)", "jawaban": "SD[cite: 4]"},
  {"pertanyaan": "中学校 (ちゅうがっこう)", "jawaban": "SMP[cite: 4]"},
  {"pertanyaan": "待ちます (まちます)", "jawaban": "Menunggu[cite: 4]"},
  {"pertanyaan": "止まります (とまります)", "jawaban": "Berhenti[cite: 4]"},
  {"pertanyaan": "食事 (しょくじ)", "jawaban": "Makan Bersama[cite: 4]"},
  {"pertanyaan": "友達 (ともだち)", "jawaban": "Teman[cite: 4]"},
  {"pertanyaan": "高校 (こうこう)", "jawaban": "SMA[cite: 4]"},
  {"pertanyaan": "仕事 (しごと)", "jawaban": "Pekerjaan[cite: 4]"},
  {"pertanyaan": "出張 (しゅっちょう)", "jawaban": "Dinas luarkota[cite: 4]"},
  {"pertanyaan": "料理 (りょうり)", "jawaban": "Masakan[cite: 4]"},
  {"pertanyaan": "楽しい (たのしい)", "jawaban": "Gembira[cite: 4]"},
  {"pertanyaan": "空港 (くうこう)", "jawaban": "Bandara[cite: 4]"},
  {"pertanyaan": "味 (あじ)", "jawaban": "Rasa[cite: 4]"},
  {"pertanyaan": "週 (しゅう)", "jawaban": "Minggu[cite: 4]"},
  {"pertanyaan": "出発 (しゅっぱつ)", "jawaban": "Keberangkatan[cite: 4]"},
  {"pertanyaan": "色 (いろ)", "jawaban": "Warna[cite: 4]"},
  {"pertanyaan": "一回 (いっかい)", "jawaban": "~kali[cite: 4]"},
  {"pertanyaan": "到着 (とうちゃく)", "jawaban": "Kedatangan[cite: 4]"},
  {"pertanyaan": "野菜 (やさい)", "jawaban": "Sayuran[cite: 4]"},
  {"pertanyaan": "食べ物 (たべもの)", "jawaban": "Makanan[cite: 4]"},
  {"pertanyaan": "午前 (ごぜん)", "jawaban": "AM[cite: 4]"},
  {"pertanyaan": "少し (すこし)", "jawaban": "Sedikit[cite: 4]"},
  {"pertanyaan": "飲み物 (のみもの)", "jawaban": "Minuman[cite: 4]"},
  {"pertanyaan": "午後 (ごご)", "jawaban": "PM[cite: 4]"},
  {"pertanyaan": "中 (なか)", "jawaban": "Dalam[cite: 4]"},
  {"pertanyaan": "お茶 (おちゃ)", "jawaban": "Teh Hijau[cite: 4]"},
  {"pertanyaan": "自分 (じぶん)", "jawaban": "Sendiri[cite: 4]"},
  {"pertanyaan": "入っています (はいっています)", "jawaban": "Masuk[cite: 4]"},
  {"pertanyaan": "お酒 (おさけ)", "jawaban": "Sake[cite: 4]"},
  {"pertanyaan": "電話 (でんわ)", "jawaban": "Telepon[cite: 4]"},
  {"pertanyaan": "会社 (かいしゃ)", "jawaban": "Perusahaan[cite: 4]"},
  {"pertanyaan": "作ります (つくります)", "jawaban": "Membuat[cite: 4]"},
  {"pertanyaan": "電気 (でんき)", "jawaban": "Listrik[cite: 4]"},
  {"pertanyaan": "本社 (ほんしゃ)", "jawaban": "Kantor Pusat[cite: 4]"},
  {"pertanyaan": "持っていきます (もっていきます)", "jawaban": "Membawa pergi[cite: 4]"},
  {"pertanyaan": "電車 (でんしゃ)", "jawaban": "Kereta[cite: 4]"},
  {"pertanyaan": "支社 (ししゃ)", "jawaban": "Kantor Cabang[cite: 4]"},
  {"pertanyaan": "お願いします (おねがいします)", "jawaban": "Tolong[cite: 4]"}
];

const output = input.map(item => {
  let jp = "";
  let romaji = "";
  
  // Parse "卵 (たまご)" -> jp: "卵", romaji: "たまご"
  const pMatch = item.pertanyaan.match(/^(.+?)\s*\((.+?)\)$/);
  if (pMatch) {
    jp = pMatch[1].trim();
    romaji = pMatch[2].trim();
  } else {
    jp = item.pertanyaan.trim();
  }
  
  // Parse "Telur[cite: 4]" -> "Telur"
  let idTrans = item.jawaban.replace(/\[cite:\s*\d+\]/g, '').trim();
  
  return {
    jp: jp,
    romaji: romaji,
    id_translation: idTrans,
    category: "KANJI (JFT)"
  };
});

fs.writeFileSync('src/data/flashcardkanjin4(jft)2.json', JSON.stringify(output, null, 2), 'utf-8');
console.log("Successfully parsed and wrote " + output.length + " items.");
